### ISSUE TITLE
Schnelles Schwimmen (Allgemein) basiert auf Athletik nicht Akrobatik

### ISSUE THREAD

**Issue by timsegger** [Foundry-VTT-PF2-German/lang-de-pf2e#517]
> Besitzt du den Kompetenzgrad Legende in **Akrobatik**, dann entspricht deine Bewegungsrate für Schwimmen deiner vollen Bewegungsrate am Boden.

Sollte in **Athletik** heißen.

**Comment by Foundry-VTT-PF2-German** [comment]
Danke für den Hinweis - ist mit dem nächsten Release gefixt.
