### ISSUE TITLE
Psioniker ist nicht verfügbar

### ISSUE THREAD

**Issue by Sulphuratum** [Foundry-VTT-PF2-German/lang-de-pf2e#558]
Wenn die deutsche Übersetzung für PF2E aktiviert ist, fehlt die Psychic/Psioniker Klasse im Kompendium und somit der Klassenauswahl. Die Klassenfeatures sind noch auffindbar.

**Comment by MSAbaddon** [comment]
Die deutsche Übersetzung des Psychic ist nicht Psioniker, sondern Mentalist:

![image](https://github.com/Foundry-VTT-PF2-German/lang-de-pf2e/assets/66370966/8257163d-e81d-4381-924b-92c217c99961)
