### ISSUE TITLE
Klassenbeschreibung Zauberer

### ISSUE THREAD

**Issue by Fenaldar** [Foundry-VTT-PF2-German/lang-de-pf2e#581]
Hallo,

in der Klassenbeschreibung des Zauberers bei den bekannten Zaubern ist die Stufennnummerierung fehlerhaft:

![Zauberer Klassenbeschreibung](https://github.com/Foundry-VTT-PF2-German/lang-de-pf2e/assets/49685258/e8585422-c4d8-4f53-b018-708ab890d01a)

**Comment by MSAbaddon** [comment]
Danke für den Hinweis - ist mit dem nächsten Release korrigiert.
