### ISSUE TITLE
Schreckensgewölbe Kompendium: Graulgust fehlt

### ISSUE THREAD

**Issue by Bendakson** [Foundry-VTT-PF2-German/lang-de-pf2e#628]
Im Kompendium fehlt die lokalisierte Version von Graulgust im Schreckensgewölbe, Ebene 2

**Comment by Bendakson** [comment]
Ebenso wie die Majordomo

**Comment by MSAbaddon** [comment]
Das ist nichts, was über das freie DE-Modul behebbar wäre - hier sind im Abenteuermodul Akteursdaten in den nicht verlinkten Tokens direkt in der Szene enthalten. Das freie DE-Modul beinhaltet nur die Übersetzung des Kompendiums, aber keine vollständige Lokalisation des Abenteuermoduls, das ist dann Teil des aktuell in Arbeit befindlichen Premium Moduls.
