### ISSUE TITLE
Falsche Variante des Generalschlüssels

### ISSUE THREAD

**Issue by Bendakson** [Foundry-VTT-PF2-German/lang-de-pf2e#648]
Der "Generalschlüssel, Einfacher" müsste "Generalschlüssel, Durchschnittlich" heißen

**Comment by Bendakson** [comment]
"Generalschlüssel, Durchschnittlicher" natürlich

**Comment by MSAbaddon** [comment]
Hm, im Englischen gibt es das garnicht - dort existiert nur ein "Skeleton Key" und ein "Greater Skeleton Key". Ich passe das entsprechend an.
