### ISSUE TITLE
"Schadenswurf"-Dialog zeigt nicht alle Felder an.

### ISSUE THREAD

**Issue by hirnstrudel** [Foundry-VTT-PF2-German/lang-de-pf2e#664]
**Version**
Foundry: 11.315
PF2e System: 5.15.3

**Aktive Module**
German [Pathfinder 2e]: 5.15.3.1
Babele: 2.5.3
libWrapper: 1.12.13.0

**Beschreibung**
Im "Schadenswurf"-Dialog sind im Abschnitt Grundschaden nicht alle Felder sichtbar:
![image](https://github.com/Foundry-VTT-PF2-German/lang-de-pf2e/assets/10131933/0a4d31a4-2821-4e3c-8260-75e45825403b)

Im Vergleich dazu der Dialog auf Englisch (ohne Module):
![image](https://github.com/Foundry-VTT-PF2-German/lang-de-pf2e/assets/10131933/ddabee13-4ad4-4340-a9a9-f5ecd9a7924a)

**Comment by MSAbaddon** [comment]
Das liegt am Design des Dialogfensters im PF2-System - das mag lange Kategorienamen in den Dropdown-Feldern nicht besonders. Ich habe jetzt einige Sachen gekürzt, ab dem nächsten Release sieht es dann folgendermaßen aus. Parallel dazu habe ich einen Issue im PF2-System angelegt in der Hoffnung, dass sie da am Design etwas abändern.
![image](https://github.com/Foundry-VTT-PF2-German/lang-de-pf2e/assets/66370966/bd119151-855e-4397-95fd-d2cb5cecbe21)

**Comment by hirnstrudel** [comment]
Hab mir schon gedacht, dass man das idealerweise im PF2-System anpasst. Aber der workaround sieht sich auch schon gut aus. Danke.
