### ISSUE TITLE
Rechtschreibfehler: "Kunsthundwerk"

### ISSUE THREAD

**Issue by Vendergast** [Foundry-VTT-PF2-German/lang-de-pf2e#67]
Bei der Auswahl des Talents Handwerksspezialist hat sich ein kleiner Rechtschreibfehler eingeschlichen. Hier steht "Kunsthundwerk" statt "Kunsthandwerk".

**Comment by MSAbaddon** [comment]
Danke für den Hinweis - wird mit dem nächsten Modul-Release korrigiert sein :-)

**Comment by Vendergast** [comment]
Immer wieder gerne :D
