### ISSUE TITLE
Falscher/Kaputter Zaubereffekt - Fehlender Willensrettungswurf: Schicksal wenden

### ISSUE THREAD

**Issue by Vendergast** [Foundry-VTT-PF2-German/lang-de-pf2e#69]
![Nudge Fate](https://github.com/Foundry-VTT-PF2-German/lang-de-pf2e/assets/134313750/59117785-4acc-49e1-afe4-cd0fd33ec676)
In der deutschen Übersetzung gibt der Zauber Schicksal wenden einen fehlenden Zaubereffekt Link aus, der nicht im Kompendium existiert.

In der englischen Originalvariante ist an der Stelle ein Will DC
![Nudge Fate - EN](https://github.com/Foundry-VTT-PF2-German/lang-de-pf2e/assets/134313750/a7ebb786-16db-4d08-bad0-a21fc3ca94ab)

**Comment by MSAbaddon** [comment]
Danke für den Hinweis, ich habe den Link entfernt. Bzgl. des Willenswurfs - das ist davon unabhängig, der Button sollte auch in der Deutschen Übersetzung angezeigt werden, wenn der Zauber tatsächlich gewirkt und dadurch in den Chat gepostet wird.
