### ISSUE TITLE
PF2-Kernregeln Seite 128: Vertrauter des Nächtlichen Pirschers

### ISSUE THREAD

**Issue by CaRuTi888** [Foundry-VTT-PF2-German/lang-de-pf2e#851]
**Aktueller Text::**
Dein Vertrauter hat dunkles Fell oder Gefieder, welches das Licht zu verschlingen scheint. Wenn du eine Hexerei wirkst oder Aufrechterhältst, während dein Vertrauter zu einem Gegner mit dem Zustand Verborgen, Versteckt oder Unentdeckt angrenzend ist, erhält der Gegner den Zustand Verängstigt 1.

**Englischer Originaltext**
Familiar of Stalking Night Your familiar is dark of fur or feather, and light seems to disappear into it. When you Cast or Sustain a hex, and your familiar is adjacent to an enemy to which it's concealed, hidden, or undetected, the enemy becomes [frightened](https://2e.aonprd.com/Conditions.aspx?ID=19) 1.

**Korrektur**
... während dein Vertrauter zu einem Gegner angrenzend ist und diesem gegenüber  dem Zustand Verborgen, Versteckt oder Unentdeckt  hat, erhält der Gegner den Zustand Verängstigt 1.

**Begrüundung** 
Der Vertraute hat den Zustand Verborgen, Versteckt oder Unentdeckt , nicht der Gegner!

**Comment by MSAbaddon** [comment]
Vielen Dank für den Hinweis - ist in den Errata auf pathfinder2.de ergänzt und mit dem nächsten Release im DE-Modul enthalten :-)
