### ISSUE TITLE
Typo: Schattenarmee

### ISSUE THREAD

**Issue by thyzerle** [Foundry-VTT-PF2-German/lang-de-pf2e#877]
Hallo zusammen,

wie handhabt ihr Tippfehler seitens Ulisses?

der Zauber Schattenarmee hat in der offiziellen Übersetzung zwar den Zustand "Verlangsamt 2" zur Auswahl, jedoch ist es im Original "slowed 1".

(Siehe: https://2e.aonprd.com/Spells.aspx?ID=994)

**Comment by MSAbaddon** [comment]
Danke für den Hinweis. Ist in der Errata-Liste auf pathfinder2.de eingearbeitet und ab dem nächsten Release auch im DE-Modul enthalten.
