### ISSUE TITLE
PF2-Kernregeln Seite 105: ENIGMAWISSEN

### ISSUE THREAD

**Issue by CaRuTi888** [Foundry-VTT-PF2-German/lang-de-pf2e#886]
Ist (Falsch): Du erlangst die Vorteile des Fertigkeitstalents Automatisches Wissen für **jedes Talent**, bei dem du Wissen abrufen nutzen kannst.
Soll (Richtig): Du erlangst die Vorteile des Fertigkeitstalents Automatisches Wissen für **jede Fertigkeit**, bei dem du Wissen abrufen nutzen kannst.

Referenz: https://2e.aonprd.com/Feats.aspx?ID=4618

**Comment by Vendergast** [comment]
In das DE-Modul eingearbeitet!
@MSAbaddon Fehlend in den Errata auf Pathfinder2.de!
