### ISSUE TITLE
PF2-Kernregeln Seite 105: WIDERHALL

### ISSUE THREAD

**Issue by CaRuTi888** [Foundry-VTT-PF2-German/lang-de-pf2e#887]
Es fehlt der Kritische Fehlschlag
Soll (aus Zusatzregeln): **Kritischer Fehlschlag** Du verstärkst ungewollt die Schallwellen, sodass du den auslösenden Schaden doppelt erleidest.

Referenz: https://2e.aonprd.com/Feats.aspx?ID=4620

**Comment by Vendergast** [comment]
@CaRuTi888 Bitte als Referenz immer die Original-Dokumente oder Offizielle Errata Nutzen. Zwar ist bei AON der Kritische Fehlschlag auch für die Remaster Version aufgeführt, dies deckt sich aber weder mit dem Original Player Core Dokument noch offiziellen Errata (zumindet habe ich dazu nichts gefunden). Im System ist daher auch die englische Version ohne Kritischen Fehlschalg eingearbeitet.
