### ISSUE TITLE
PF2-Kernregeln Seite 370: ETÜDE DES LEHRMEISTERS

### ISSUE THREAD

**Issue by CaRuTi888** [Foundry-VTT-PF2-German/lang-de-pf2e#888]
Ist (falsch): Der Zauber hat einen Aufwand von <2> Aktionen.
Soll (richtig): Der Zauber kann als Freie Aktion gewirkt werden.

Referenz: https://2e.aonprd.com/Spells.aspx?ID=1770

**Offen**: Heißt das Talent auf Seite 101 ETÜDE DES **WISSENSHÜTERS** oder ETÜDE DES **LEHRMEISTERS** (wie der Zauber).

**Comment by MSAbaddon** [comment]
Der Zauber wie auch das Talent heißt korrekt Etüde des Wissenshüters.
