### ISSUE TITLE
 PF2-Kernregeln Seite 371: NACHWIRKENDE KOMPOSITION

### ISSUE THREAD

**Issue by CaRuTi888** [Foundry-VTT-PF2-German/lang-de-pf2e#890]
Ist (falsch): Der Zauber hat keinen Aufwand
Soll (richtig): Der Zauber kann als Freie Aktion gewirkt werden.

Referenz: https://2e.aonprd.com/Spells.aspx?ID=1769

**Comment by Vendergast** [comment]
Im System richtig hinterlegt.
@MSAbaddon Fehlend in den Errata auf pathfinder2.de!
