### ISSUE TITLE
Xulgath Anführer schwächender Angriff inkorrekt

### ISSUE THREAD

**Issue by B4dHabit** [Foundry-VTT-PF2-German/lang-de-pf2e#916]
Xulgath-Anführer:
Schwächende angriff ist falsch.
In Foundry wird es als Aktion Aufgeführt und hat einen Zähigkeits saving throw.
Laut Kernregeln Monster S.347 ist es aber einfach automatisch. Ohne aktion oder save.
https://2e.aonprd.com/Monsters.aspx?ID=3246

**Comment by MSAbaddon** [comment]
Danke für den Hinweis, stelle eine entsprechende Änderung im PF2-System ein.
