### ISSUE TITLE
 PF2-Kernregeln Spieler Seite 361: UNSICHTBARKEIT

### ISSUE THREAD

**Issue by CaRuTi888** [Foundry-VTT-PF2-German/lang-de-pf2e#934]
Letzter Satz.

Ist (falsch): Erhöhung (4.) Der Zauber dauert 1 Minute, aber er endet nicht, wenn das Ziel eine **feindliche** Handlung ausführt.
Soll (richtig): Erhöhung (4.) Der Zauber dauert 1 Minute, aber er endet nicht, wenn das Ziel eine **feindselige** Handlung ausführt.

Referenz: PC1, p.340

**Comment by Vendergast** [comment]
Im System eingearbeitet @MSAbaddon bitte in die Errata übernehmen.
