### ISSUE TITLE
 PF2-Kernregeln Spieler Seite 363: VERKÖRPERUNG DER NATUR

### ISSUE THREAD

**Issue by CaRuTi888** [Foundry-VTT-PF2-German/lang-de-pf2e#935]
Grüner Mann/Grüne Liebkosung 

Ist (falsch): Grüne Liebkosung (Aura, Natur, **Verwandlung**) 18 m
Soll (richtig): Grüne Liebkosung (Aura, Natur) 18 m

Begründung: Schulen (Verwandlung) gibt es nicht mehr.

Kaiju/Trampeln ist eine <3>-Aktionen-Handlung
Ist (falsch): **Trampeln** Du bewegst dich mit maximal ...
Soll (richtig): **Trampeln <3>** Du bewegst dich mit maximal ...

Referenz: PC1, p.346

**Comment by Vendergast** [comment]
Änderung im System eingepflegt, @MSAbaddon bitte in den Errata ergänzen
