### ISSUE TITLE
 PF2-Kernregeln Spieler Seite 364: VERSCHWIMMEN

### ISSUE THREAD

**Issue by CaRuTi888** [Foundry-VTT-PF2-German/lang-de-pf2e#936]
Der Zauber hat die falschen Kategorien.

Ist (falsch): **GESTALTWANDEL** HANDHABEN KONZENTRATION **TOD**
Soll (richtig): HANDHABEN **ILLUSION** KONZENTRATION **SICHTBAR**

Referenz: PC1, p. 318

**Comment by Vendergast** [comment]
Wird vom System gehändelt; @MSAbaddon bitte in den Errata ergänzen
